const express = require('express');
const isAuth = require('../middleware/is-auth');
const router = express.Router();
const authController = require('../controllers/index');
const loginController = require('../controllers/login');
const userController = require('../controllers/user');
const indexController = require('../controllers/index');
const artistController = require('../controllers/Artist');
const trackController = require('../controllers/Track');
const albumController = require('../controllers/Album');
// router.get('/me/login',authController.getLogin);
router.get('/callback',authController.getCallback);
// router.post('/me/location',isAuth,loginController.getLocation);
router.get('/playlists',isAuth,userController.getUserPlaylist);
router.get('/new-releases',isAuth,userController.getNewReleases);
// router.get('/me',isAuth,userController.getUserProfile);
router.get('/top-artists',isAuth,userController.getTopArtists);
router.get('/artist/:artistId',isAuth,artistController.getArtistProfile);
router.get('/artist/:artistId/top-tracks',isAuth,artistController.getArtistTopTracks);
router.get('/artist/:artistId/albums',isAuth,artistController.getArtistAlbum);
router.get('/artist/:artistId/related-artists',isAuth,artistController.getRelatedArtists);
router.get('/users/:userId',isAuth,userController.getUserById);
router.get('/users/:userId/drooble-users',isAuth,userController.getDroobleUsers);
// router.put('/me/tracks/:trackId',isAuth,trackController.saveToMyTrack);
// router.delete('/me/tracks/:trackId',isAuth,trackController.removeTrackFromLibrary);
// router.put('/me/albums/:albumId',isAuth,albumController.saveAlbumToLibrary);
// router.delete('/me/albums/:albumId',isAuth,albumController.removeAlbumFromLibrary);
// router.get('/me/albums',isAuth,albumController.getUserSavedAlbum);
router.get('/featured-playlists',isAuth,userController.getFeaturedPlaylists);
module.exports = router;